version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: redis
    versions:
    - 3.1.2
  - dependency-name: "@angular-eslint/eslint-plugin"
    versions:
    - 2.0.2
    - 2.1.0
  - dependency-name: "@editorjs/editorjs"
    versions:
    - 2.20.1
  - dependency-name: "@ngrx/component-store"
    versions:
    - 11.0.1
    - 11.1.0
  - dependency-name: "@jscutlery/semver"
    versions:
    - 1.3.2
  - dependency-name: editorjs-hyperlink
    versions:
    - 1.0.5
  - dependency-name: socket.io-client
    versions:
    - 4.0.0
  - dependency-name: socket.io
    versions:
    - 4.0.0
  - dependency-name: "@commitlint/cli"
    versions:
    - 12.0.1
