version: '3'
services:
  # Web services
  api:
    build: ./api
    restart: unless-stopped
    ports:
      - '3000:3000'

  # Database services
  db-rs1:
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - /mongo/rs1/data:/data/db
      - ./db:/setup
    command: --replSet rs0

  db-rs2:
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - /mongo/rs2/data:/data/db
    command: --replSet rs0

  db-rs3:
    image: 'mongo'
    restart: unless-stopped
    volumes:
      - /mongo/rs3/data:/data/db
    command: --replSet rs0
