backend:
  name: git-gateway
  branch: main
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
  uploadMedia: Upload “{{path}}”
  deleteMedia: Delete “{{path}}”

logo_url: https://docs.cslussana.com/img/logo.png

media_folder: 'apps/docs/static/img' # Media files will be stored in the repo under apps/docs/static/img
public_folder: '/img/' # The src attribute for uploaded media will begin with /img/

collections:
  - name: category
    label: 'Categories'
    label_singular: 'Category'
    folder: apps/docs/docs
    extension: json
    create: true
    identifier_field: label
    path: '{{label}}/_category_'
    fields:
      - name: 'label'
        label: 'Label'
        widget: 'string'
      - { name: position, label: Position, widget: number }
      - name: 'link'
        label: 'Link'
        widget: 'object'
        fields:
          - name: 'type'
            label: 'Type'
            widget: 'string'
            default: 'generated-index'
          - name: 'description'
            label: 'Description'
            widget: 'string'
  - name: docs
    label: 'Docs'
    label_singular: 'Doc'
    folder: apps/docs/docs
    summary: '{{category}}/{{slug}}'
    extension: md
    create: true
    path: '{{category}}/{{slug}}'
    fields:
      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'category'
        value_field: 'label'
        search_fields: [label]
      - label: 'Slug'
        name: 'slug'
        widget: 'string'
      - { name: body, label: Body, widget: markdown, modes: [raw] }
      - label: 'Sidebar position'
        name: 'sidebar_position'
        widget: 'number'
  - name: blog
    label: 'Posts'
    label_singular: 'Post'
    folder: apps/docs/blog
    summary: '{{title}}'
    extension: md
    widget: 'list'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown, modes: [raw] }
      - { name: slug, label: Slug, widget: string }
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
      - label: 'Authors'
        name: 'authors'
        widget: 'list'
        fields:
          - { name: name, label: Name, widget: string }
          - { name: title, label: Title, widget: string }
          - { name: url, label: URL, widget: string }
          - { name: image_url, label: Image URL, widget: string }
