backend:
  name: git-gateway
  branch: main
  create: Create {{collection}} “{{slug}}”
  update: Update {{collection}} “{{slug}}”
  delete: Delete {{collection}} “{{slug}}”
  uploadMedia: Upload “{{path}}”
  deleteMedia: Delete “{{path}}”

local_backend: true

logo_url: https://docs.cslussana.com/img/logo.png

media_folder: 'apps/docs/static/img' # Media files will be stored in the repo under apps/docs/static/img
public_folder: '/img/' # The src attribute for uploaded media will begin with /img/

collections:
  - name: category
    label: 'Categories'
    label_singular: 'Category'
    folder: apps/docs/docs
    extension: json
    create: true
    identifier_field: label
    path: '{{label}}/_category_'
    editor:
      preview: false
    fields:
      - name: 'label'
        label: 'Label'
        widget: 'string'
        hint: 'The title at the top of the category page and the label in the sidebar.'
      - name: position
        label: Position
        widget: number
      - name: 'link'
        label: 'Link'
        widget: 'object'
        fields:
          - name: 'type'
            label: 'Type'
            widget: 'hidden'
            default: 'generated-index'
          - name: 'description'
            label: 'Description'
            widget: 'string'
            hint: Description shown in the category page.

  - name: docs
    label: 'Docs'
    label_singular: 'Doc'
    folder: apps/docs/docs
    summary: '{{dirname}}/{{filename}}'
    extension: md
    create: true
    path: '{{category}}/{{filename}}'
    sortable_fields: ['filename', 'category', 'sidebar_position']
    fields:
      - label: 'Category'
        name: 'category'
        widget: 'relation'
        collection: 'category'
        value_field: 'label'
        search_fields: [label]
        required: false
      - label: File name
        name: filename
        widget: string
        hint: This is the name of the new file, without the extension. If category is set, its path will be "CATEGORY/FILENAME.md."
      - name: body
        label: Body
        widget: markdown
        modes: [raw]
      - label: 'Sidebar position'
        name: 'sidebar_position'
        widget: 'number'
        hint: 'This value controls the order in which docs appear in the sidebar and in category pages.'

  - name: blog
    label: 'Posts'
    label_singular: 'Post'
    folder: apps/docs/blog
    identifier_field: title
    extension: md
    widget: 'list'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      - { name: title, label: Title, widget: string }
      - { name: body, label: Body, widget: markdown, modes: [raw] }
      - { name: slug, label: Slug, widget: string }
      - label: 'Tags'
        name: 'tags'
        widget: 'list'
      - label: 'Authors'
        name: 'authors'
        widget: 'list'
        fields:
          - name: key
            label: Author key
            widget: select
            options: [luca]
            required: false
            hint: You can select one of the pre-existing authors.
          - name: name
            label: Name
            widget: string
            required: false
          - name: title
            label: Title
            widget: string
            required: false
          - name: url
            label: URL
            widget: string
            required: false
          - name: image_url
            label: Image URL
            widget: string
            required: false
