name: Deploy App

on:
  push:
    tags:
      - v*

jobs:
  dokku-deploy:
    name: Deploy to Dokku
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: idoberko2/dokku-deploy-github-action@v1
        with:
          ssh-private-key: ${{ secrets.DOKKU_SSH_KEY }}
          dokku-host: 'cslussana-test.tk'
          app-name: 'api'