name: Deploy

on:
  push:
    tags:
      - v*

jobs:
  api-deploy:
    name: API
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js v12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: Install dependencies
        run: yarn install --ignore-scripts
      - name: Build
        run: yarn nx build api --prod
      - name: Restart service
        run: pm2 restart api
