name: Create release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git user to "🤖 CSL Bot"
        shell: bash
        run: git config user.email "-" && git config user.name "🤖 CSL Bot"

      - name: Install packages
        shell: bash
        run: yarn install

      - name: Bump project version and release
        shell: bash
        run: yarn nx run workspace:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
