name: Create release

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git user to "🤖 CSL Bot"
        shell: bash
        run: git config user.email "-" && git config user.name "🤖 CSL Bot"

      - name: Install packages
        shell: bash
        run: yarn install --frozen-lockfile --non-interactive

      - name: Create release
        shell: bash
        run: yarn nx run workspace:version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag last-release
        shell: bash
        run: git tag -f last-release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
