name: Create release

on:
  push:
    tags:
      - v*

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout all commits
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup git user to "🤖 CSL Bot"
        shell: bash
        run: git config user.email "-" && git config user.name "🤖 CSL Bot"

      # Old release method
      - name: Create release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

      # New release method. Doesn't work at the moment
      # - name: Install packages
      #   shell: bash
      #   run: yarn install --frozen-lockfile --non-interactive

      # - name: Create release
      #   shell: bash
      #   run: yarn nx run workspace:version
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag last-release
        shell: bash
        run: git tag -f last-release

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
          force: true
          tags: true
